In [ ]:
# Prior to running pip install all modules in requirements.txt using the following command:
# pip install -r requirements.txt

###### To run locally ######
# Pull the latest commits.
# change working directory to flask_app/
# use the following command:
# flask run
# you can now test the app on http://127.0.0.1:5000/

# if you get a 403 error (Access to 127.0.0.1 was denied), you may need to clear cookies.

from flask import Flask
import sqlite3

app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Welcome to Pollaris!'

@app.route('/login')
def log_in():
    conn = sqlite3.connect(user_table)
    c = conn.cursor()

    c.execute("CREATE TABLE Users(UserID INT, UserName VARCHAR(8), Password VARCHAR(30));")
    
    users = [(1, 'abcd1111', 'ABC123'), (2, 'efgh2222', 'XYZ789'), (3, 'ijkl3333', '123AAA')]
    
    for user in users:
        item_no, categ, desc = user
        c.execute("INSERT INTO Users VALUES (?, ?, ?);", (item_no, categ, desc))
    
    c.execute("SELECT * FROM Users;")

    conn.commit()
    conn.close()
    
    return "This is where you will log in!"

@app.route('/signup')
def sign_up():
#     conn = psycopg2.connect('postgres://lab10_db_pvd9_user:Ye7i4QvXGpsZkSQbZ6Es7wFZpGUfHWyC@dpg-cl3rea1novjs73bnl7n0-a/lab10_db_pvd9')
#     cur = conn.cursor()
#     cur.execute('''
#     CREATE TABLE IF NOT EXISTS Basketball(
#         First varchar(255),
#         Last varchar(255),
#         City varchar(255),
#         Name varchar(255),
#         Number int
#         );
#         ''')
#     conn.commit()
#     conn.close()
    return "This is where you will create a new account!"

@app.route('/take')
def take_a_poll():
#     conn = psycopg2.connect('postgres://lab10_db_pvd9_user:Ye7i4QvXGpsZkSQbZ6Es7wFZpGUfHWyC@dpg-cl3rea1novjs73bnl7n0-a/lab10_db_pvd9')
#     cur = conn.cursor()
#     cur.execute('''
#         INSERT INTO Basketball (First, Last, City, Name, Number)
#             Values
#             ('Jayson', 'Tatum', 'Boston', 'Celtics', 0),
#             ('Stephen', 'Curry', 'San Francisco', 'Warriors', 30),
#             ('Nikola', 'Jokic', 'Denver', 'Nuggets', 15),
#             ('Kawhi', 'Leonard', 'Los Angeles', 'Clippers', 2);
#         ''')
#     conn.commit()
#     conn.close()
    return "This is where you will be able to find a poll to take!"


@app.route('/user')
def user_dashboard():
#     conn = psycopg2.connect('postgres://lab10_db_pvd9_user:Ye7i4QvXGpsZkSQbZ6Es7wFZpGUfHWyC@dpg-cl3rea1novjs73bnl7n0-a/lab10_db_pvd9')
#     cur = conn.cursor()
#     cur.execute('''
#         SELECT * FROM Basketball;
#         ''')
#     records = cur.fetchall()
#     conn.close()
#     response_string=""
#     response_string+="<table>"
#     for player in records:
#         response_string+="<tr>"
#         for info in player:
#             response_string+="<td>{}</td>".format(info)
#         response_string+="</tr>"
#     response_string+="</table>"
    return "This is your dashboard where you will be able to access all of your polls and history"

@app.route('/create')
def create_poll():
#     conn = psycopg2.connect('postgres://lab10_db_pvd9_user:Ye7i4QvXGpsZkSQbZ6Es7wFZpGUfHWyC@dpg-cl3rea1novjs73bnl7n0-a/lab10_db_pvd9')
#     cur = conn.cursor()
#     cur.execute('''
#         DROP TABLE Basketball;
#         ''')
#     conn.commit()
#     conn.close()
    return "This is where you will create a new poll!"

In [1]:
import sqlite3

In [4]:
conn = sqlite3.connect("db", timeout=10)
c = conn.cursor()
c.execute("DROP TABLE if EXISTS Users")

c.execute("CREATE TABLE Users(UserID INT, UserName VARCHAR(8), Password VARCHAR(30));")

users = [(1, 'abcd1111', 'ABC123'), (2, 'efgh2222', 'XYZ789'), (3, 'ijkl3333', '123AAA')]

for user in users:
    item_no, categ, desc = user
    c.execute("INSERT INTO Users VALUES (?, ?, ?);", (item_no, categ, desc))
conn.commit()

a = c.execute('''SELECT * FROM Users;''')
print("Users:", a.fetchall())

conn.close()

Users: [(1, 'abcd1111', 'ABC123'), (2, 'efgh2222', 'XYZ789'), (3, 'ijkl3333', '123AAA')]

In [ ]:
conn = sqlite3.connect("db")
c = conn.cursor()

users = [(1, 'abcd1111', 'ABC123'), (2, 'efgh2222', 'XYZ789'), (3, 'ijkl3333', '123AAA')]

for user in users:
    item_no, categ, desc = user
    c.execute("INSERT INTO Users VALUES (?, ?, ?);", (item_no, categ, desc))
conn.commit()

a = c.execute('''SELECT * FROM Users;''')
print(a.fetchall())

conn.close()

In [ ]:
print(a.fetchall())